
$(document).ready(function(){

//$("body").prepend("<div class=\"header-wrapper prefix-clear\"><div class=\"main-content\" style=\"margin: auto;\"><div class=\"account-wrapper toRight\"><div class=\"account-wrapper\"><ul class=\"account-container\"><li><a class=\"\" href=\"#\">New Listing</a></li><li class=\"account-notify\"><a class=\"\" href=\"#\"><i class=\"fa fa-bell\"></i></a></li><li class=\"account-profile menu-wrapper\"><span class=\"account-avatar\"><img src=\"images/1.jpg\"/></span><span>Derek Nguyen</span><i class=\"fa fa-sort-desc\"></i><div class=\"menu\"><div class=\"menu-content\"><ul><li><a href=\"#\">Account Setting</a></li><li><a href=\"#\">Billing & Payment</a></li><li><a href=\"#\">Account Setting</a></li><li><hr/><a href=\"#\">Logout</a></li></ul></div></div></li></ul></div></div><h1 class=\"toLeft\" id=\"logo\"><a href=\"browse.html\">Mingo</a></h1><div class=\"header-nav\"><ul><li class=\"menu-wrapper\"><a href=\"#\">Browse&nbsp;&nbsp;<i class=\"fa fa-sor-desc\"></i></a><div class=\"menu mn200\"><div class=\"menu-content\"><ul><li><a href=\"#\">Account Setting</a></li><li><a href=\"#\">Billing & Payment</a></li><li><a href=\"#\">Account Setting</a></li><li><a href=\"#\">Logout</a></li></ul></div></div></li></ul></div></div></div>");

$("body")
		//.append("<div id=\"footer\" class=\"footer\"><div class=\"main-content\"><div class=\"col-wrapper\"><div class=\"col-2\"><div class=\"col-wrapper\"><div class=\"col-2\"><div class=\"p5\"><h3>About Mingofy</h3><ul><li><a href=\"#\">How It works</a></li><li><a href=\"about.html\">About Us</a></li><li><a href=\"#\">Blog</a></li><li><a href=\"#\">Press</a></li></ul></div></div><div class=\"col-2\"><div class=\"p5\"><h3>Support</h3><ul><li><a href=\"#\">Seller Handbook</a></li><li><a href=\"#\">Buyer HandBook</a></li><li><a href=\"#\">Help & Support</a></li><li><a href=\"#\">Contact Us</a></li></ul></div></div></div></div><div class=\"col-2\"><div class=\"col-wrapper\"><div class=\"col-2\"><div class=\"p5\"><h3>Discover</h3><ul><li><a href=\"#\">Browse All Categories</a></li></ul></div></div></div></div></div><div class=\"footer-note\"><span class=\"toRight p10\">&copy; 2015 Mingofy, Inc.</span><ul class=\"inline\"><li><a href=\"#\">Terms of Use</a></li><li><a href=\"#\">Privacy Policy</a></li><li><a href=\"#\">Partner Terms</a></li></ul></div></div></div>")
		//.prepend("<div id=\"header-wrapper\" class=\"header-wrapper\"><ul id=\"hacc-wrapper\"><li><a class=\"hacc-feed\" href=\"#\">New Listing</a></li><li><a href=\"#\"><i class=\"fa fa-bell\"></i></a></li><li id=\"hacc-nav-wrapper\"><div id=\"hacc-ava\"><a href=\"#\" title=\"dashboard\"><img alt=\"Dashboard\" src=\"images/1.jpg\"/></a></div><div class=\"hacc-nav\"><div class=\"hacc-nav-content\"><ul><li><a href=\"dashboard.html\">Dashboard</a></li><li><a href=\"#\">My Subscriptions</a></li><li><a href=\"#\">Account</a></li><li><form><button>Logout</button></form></li></ul></div></div></li></ul><h1 id=\"hlogo\"><a href=\"browse.html\">Mingofy</a></h1><div id=\"hsearch\"><form><button><i class=\"fa fa-search\"></i></button><input type=\"text\" /></form></div></div><div id=\"hlower-wrapper\"><div id=\"hlower-content\"><div class=\"hnav-wrapper\"><p>Home Supply</p><div class=\"hnav-menu\"><div class=\"hnav-menu-content\"><ul><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li></ul></div></div></div><div class=\"hnav-wrapper\"><p>Beauty & Health</p><div class=\"hnav-menu\"><div class=\"hnav-menu-content\"><ul><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li></ul></div></div></div><div class=\"hnav-wrapper\"><p>Clothing</p><div class=\"hnav-menu\"><div class=\"hnav-menu-content\"><ul><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li><li><a href=\"#\">Home Supply</a></li></ul></div></div></div></div></div>")
		.prepend("<div id=\"header-wrapper\" class=\"header-wrapper\"><div id=\"header-container\"><ul id=\"hacc-wrapper\"><li><a href=\"#\"><i class=\"fa fa-bell1\"></i></a></li><li><a href=\"#\"><i class=\"fa fa-shopping-cart1\"></i></a></li><li id=\"hacc-nav-wrapper\"><div id=\"hacc-ava\"><a href=\"#\" title=\"dashboard\"><img alt=\"Dashboard\" src=\"images/1.jpg\"/></a></div><div class=\"hacc-nav\"><div class=\"hacc-nav-content\"><ul><li><a href=\"dashboard.html\">Dashboard</a></li><li><a href=\"#\">My Subscriptions</a></li><li><a href=\"#\">Account setting</a></li><li><a href=\"#\">Help Center</a></li><li><form><button>Logout</button></form></li></ul></div></div></li></ul><h1 id=\"hlogo\"><a href=\"browse.html\">Mingofy</a></h1><a id=\"hdiscover\" href=\"#\"><strong>Discover</strong></a><div id=\"hsearch\"><form><button><i class=\"fa fa-search\"></i></button><input type=\"text\" /></form></div></div></div>")
		;

//$("#acc-nav").append("<div class=\"main-content1\"><div class=\"dashboard-profile\"><ul class=\"toRight toCenter\"><li><a class=\"round-btn twhite\" href=\"setting.html\"><i class=\"fa fa-cog\">&nbsp;&nbsp;Setting</i></a></li></ul><div class=\"profile-info\"><h3 class=\"fnor\">Derek Nguyen</h3></div><div class=\"p5 profile-holder\"><div class=\"profile-ava\"><img id=\"ava-img-holder\" src=\"images/user1.png\" /></div></div> <div class=\"dashboard-nav-wrapper\"><div class=\"dashboard-nav\"><ul><li><a  href=\"dashboard.html\">Dashboard</a></li><li><a class=\"active\" href=\"subscriptions.html\">Your Subscriptions</a></li><li><a href=\"listing.html\">Your Listings</a></li><li><a href=\"order.html\">Your Orders</a></li><li><a href=\"transaction.html\">Transactions</a></li></ul></div></div></div></div>");


});




