<option value="0">Select State</option>
<option value="al">AL - Alabama</option>
<option value="ak">AK - Alaska</option>
<option value="az">AZ - Arizona</option>
<option value="ar">AR - Arkansas</option>
<option value="ca">CA - California</option>
<option value="co">CO - Colorado</option>
<option value="ct">CT - Connecticut</option>
<option value="de">DE - Delaware</option>
<option value="fl">FL - Florida</option>
<option value="ga">GA - Georgia</option>
<option value="hi">HI - Hawaii</option>
<option value="id">ID - Idaho</option>
<option value="il">IL - Illinois</option>
<option value="in">IN - Indiana</option>
<option value="ia">IA - Iowa</option>
<option value="ks">KS - Kansas</option>
<option value="ky">KY - Kentucky</option>
<option value="la">LA - Louisiana</option>
<option value="me">ME - Maine</option>
<option value="md">MD - Maryland</option>
<option value="ma">MA - Massachusetts</option>
<option value="mi">MI - Michigan</option>
<option value="mn">MN - Minnesota</option>
<option value="ms">MS - Mississippi</option>
<option value="mo">MO - Missouri</option>
<option value="mt">MT - Montana</option>
<option value="ne">NE - Nebraska</option>
<option value="nv">NV - Nevada</option>
<option value="nh">NH - New Hampshire</option>
<option value="nj">NJ - New Jersey</option>
<option value="nm">NM - New Mexico</option>
<option value="ny">NY - New York</option>
<option value="nc">NC - North Coralina</option>
<option value="nd">ND - North Dakota</option>
<option value="oh">OH - Ohio</option>
<option value="ok">OK - Oklahoma</option>
<option value="or">OR - Oregon</option>
<option value="pa">PA - Pennsylvania</option>
<option value="ri">RI - Rhode Island</option>
<option value="sc">SC - South Coralina</option>
<option value="sd">SD - South Dakota</option>
<option value="tn">TN - Tennessee</option>
<option value="tx">TX - Texas</option>
<option value="ut">UT - Utah</option>
<option value="vt">VT - Vermont</option>
<option value="va">VA - Virginia</option>
<option value="wa">WA - Washington</option>
<option value="wv">WV - West Virginia</option>
<option value="wi">WI - Wisconsin</option>
<option value="wy">WY - Wyoming</option>
